[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hobby-recommender"
version = "1.0.0"
description = "AI-powered hobby recommendation system"
requires-python = ">=3.10" 